apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-mariadb
  template:
    metadata:
      labels:
        app: wordpress-mariadb
    spec:
      containers:
        - name: wordpress
          image: wordpress:latest
          resources:
            requests:
              memory: 200Mi
              cpu: 300m
            limits:
              memory: 512Mi
              cpu: 1000m
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: mariadb
            - name: WORDPRESS_DB_USER
              value: dbuser
            - name: WORDPRESS_DB_PASSWORD
              value: dbuser@123
            - name: WORDPRESS_DB_NAME
              value: wordpress

---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-mariadb-svc
spec:
  selector:
    app: wordpress-mariadb
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "ebs-sc"  # Update this with the correct storage class
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
spec:
  serviceName: "mariadb-headless"
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: dbuser@123
        - name: MYSQL_DATABASE
          value: wordpress
        - name: MYSQL_USER
          value: dbuser
        - name: MYSQL_PASSWORD
          value: dbuser@123
        volumeMounts:
        - name: mariadb-pvc
          mountPath: /var/lib/mysql
          subPath: mariadb-data
  volumeClaimTemplates:
  - metadata:
      name: mariadb-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc"  # Update this with the correct storage class
      resources:
        requests:
          storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-svc
spec:
  selector:
    app: mariadb
  type: ClusterIP
  ports:
    - name: mariadb-port
      port: 3306
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-headless
spec:
  clusterIP: None
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: 3306




  
